# Generated by Django 5.2.9 on 2026-01-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_code', models.CharField(max_length=10)),
                ('no_of_teachers', models.IntegerField()),
                ('hod', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10)),
                ('emp_no', models.IntegerField()),
                ('ts_no', models.IntegerField()),
                ('nrc_no', models.CharField(max_length=20, unique=True)),
                ('tcz_no', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('acad_qualif', models.CharField(max_length=16)),
                ('prof_qualif', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=50)),
                ('minor', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=14)),
                ('pay_point', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('date_first_app', models.DateField()),
                ('date_current_app', models.DateField()),
                ('date_retirement', models.DateField()),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
                ('updation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
