# Generated by Django 5.2.9 on 2026-02-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='classes',
            field=models.ManyToManyField(blank=True, to='ResultsApp.class'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='ResultsApp.subject'),
        ),
    ]
