# Generated by Django 5.2.9 on 2026-02-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0002_teacherprofile_classes_teacherprofile_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects',
        ),
    ]
