# Generated by Django 5.2.9 on 2026-01-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0002_department_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_numeric',
        ),
        migrations.AddField(
            model_name='class',
            name='numeric_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
