# Generated by Django 5.2.9 on 2026-01-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0003_remove_class_class_numeric_class_numeric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='numeric_name',
            field=models.IntegerField(default='N/A'),
        ),
    ]
