# Generated by Django 5.2.9 on 2026-02-03 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0003_remove_teacherprofile_classes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior'), ('Upper Primary', 'Upper Primary'), ('Lower Primary', 'Lower Primary'), ('ECE', 'ECE')], max_length=50)),
                ('file', models.FileField(upload_to='student_materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Syllabi', 'Syllabi'), ('Schemes of Work', 'Schemes of Work'), ('Lesson Plans', 'Lesson Plans'), ('Modules', 'Modules'), ('Templates', 'Templates'), ('Past Papers', 'Past Papers'), ('Books', 'Books'), ('Miscellaneous', 'Miscellaneous')], max_length=50)),
                ('file', models.FileField(upload_to='teacher_materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
