# Generated by Django 5.2.9 on 2026-01-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0004_alter_class_numeric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='numeric_name',
            field=models.IntegerField(),
        ),
    ]
