# Generated by Django 5.2.9 on 2026-02-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0004_studentmaterial_teachermaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmaterial',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Student Material', 'verbose_name_plural': 'Student Materials'},
        ),
        migrations.AlterModelOptions(
            name='teachermaterial',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Teacher Material', 'verbose_name_plural': 'Teacher Materials'},
        ),
        migrations.AlterField(
            model_name='studentmaterial',
            name='level',
            field=models.CharField(choices=[('ECE', 'Early Childhood Education'), ('Lower Primary', 'Lower Primary'), ('Upper Primary', 'Upper Primary'), ('Junior', 'Junior Secondary'), ('Senior', 'Senior Secondary')], max_length=50),
        ),
    ]
