# Generated by Django 5.2.9 on 2026-01-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0005_alter_class_numeric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='numeric_name',
            field=models.IntegerField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='subjectcombination',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResultsApp.class'),
        ),
        migrations.AlterField(
            model_name='subjectcombination',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResultsApp.subject'),
        ),
    ]
