# Generated by Django 5.2.9 on 2026-02-04 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0006_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('material_file', models.FileField(upload_to='learning_materials/')),
                ('class_level', models.CharField(choices=[('ECE', 'ECE'), ('LOWER_PRIMARY', 'Lower Primary'), ('UPPER_PRIMARY', 'Upper Primary'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='ResultsApp.class'),
        ),
    ]
