# Generated by Django 5.2.9 on 2026-01-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0006_alter_class_numeric_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcombination',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ResultsApp.class'),
        ),
        migrations.AlterField(
            model_name='subjectcombination',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ResultsApp.subject'),
        ),
    ]
