# Generated by Django 5.2.9 on 2026-01-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0007_alter_subjectcombination_student_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcombination',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResultsApp.class'),
        ),
        migrations.AlterField(
            model_name='subjectcombination',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResultsApp.subject'),
        ),
    ]
