# Generated by Django 5.2.9 on 2026-02-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0007_learningmaterial_alter_student_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='classes',
            field=models.ManyToManyField(blank=True, to='ResultsApp.class'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='ResultsApp.subject'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='disability',
            field=models.CharField(choices=[('none', 'None'), ('physical', 'Physical'), ('visual', 'Visual'), ('hearing', 'Hearing')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='nationality',
            field=models.CharField(choices=[('ZAMBIAN', 'Zambian'), ('FOREIGN', 'Foreign')], default=3, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, choices=[('PARENT', 'Parent'), ('SPOUSE', 'Spouse'), ('SIBLING', 'Sibling'), ('CHILD', 'Child'), ('GUARDIAN', 'Guardian'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
