# Generated by Django 5.2.9 on 2026-04-20 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0008_teacherprofile_classes_teacherprofile_subjects_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('week', models.CharField(max_length=10)),
                ('work_done', models.TextField()),
                ('work_not_done', models.TextField(blank=True)),
                ('teacher_comments', models.TextField(blank=True)),
                ('hod_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
