# Generated by Django 5.2.9 on 2026-01-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0008_alter_subjectcombination_student_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dod',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='roll_id',
            new_name='exam_no',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='phone_no',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='numeric_name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=10),
        ),
    ]
