# Generated by Django 5.2.9 on 2026-01-08 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0009_rename_dod_student_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exam_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResultsApp.class'),
        ),
    ]
