# Generated by Django 5.2.9 on 2026-01-08 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0010_alter_student_exam_no_alter_student_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exam_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ResultsApp.class'),
        ),
    ]
