# Generated by Django 5.2.9 on 2026-04-28 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0010_historicalresult_is_absent_result_is_absent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResultsApp.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResultsApp.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResultsApp.teacherprofile')),
            ],
            options={
                'unique_together': {('teacher', 'subject', 'assigned_class')},
            },
        ),
    ]
