# Generated by Django 5.2.9 on 2026-01-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '000X_auto_something'),
        ('ResultsApp', '0014_rename_test_type_result_assessment_type_and_more'),
    ]

    operations = [
    ]
