# Generated by Django 5.2.9 on 2026-01-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0015_merge_20260110_2343'),
    ]

    operations = [
    ]
