# Generated by Django 5.2.9 on 2026-01-12 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0018_alter_result_term_alter_result_test_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10)),
                ('emp_no', models.IntegerField()),
                ('phone_no', models.CharField(max_length=14)),
                ('date_first_app', models.DateField()),
                ('date_current_app', models.DateField()),
                ('date_retirement', models.DateField()),
                ('acad_qualif', models.CharField(max_length=50)),
                ('prof_qualif', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=50)),
                ('minor', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ResultsApp.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='no_of_teachers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ResultsApp.department'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
