# Generated by Django 5.2.9 on 2026-01-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0019_teacherprofile_delete_teacher_subject_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
