# Generated by Django 5.2.9 on 2026-01-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsApp', '0020_notice_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='date_retirement',
            new_name='date_of_retirement',
        ),
    ]
